name: Generate site
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          composer install
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache-dependency-path: ./package.json
          cache: 'npm'
      - name: Generate repos
        run: |
          GITHUB_TOKEN=${{github.token}} npm run generate
      - name: Build production
        run: |
          npm run prod
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_production/
      